# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(default=0)),
                ('item_type', models.CharField(max_length=200)),
                ('item_name', models.CharField(max_length=200)),
            ],
        ),
    ]
