# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_id',
        ),
    ]
