# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_itemparams'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemParams',
            new_name='ItemParam',
        ),
    ]
