# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20170825_1020'),
        ('recipes', '0003_auto_20170828_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='item',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='items.Item'),
            preserve_default=False,
        ),
    ]
